version: '3.3'
services:
  mongo:
    image: mongo
    ports:
      - '27017:27017'
    container_name: haevn-db-mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root