version: '3.3'
services:
  maria:
    image: mariadb
    ports:
      - '3306:3306'
    container_name: haevn-db-maria
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=
      - MYSQL_USER=app
      - MYSQL_PASSWORD=