name: Maven CI/CD

on:
 workflow_dispatch:
 pull_request:
    branches: [ master ]

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 21
      uses: actions/setup-java@v1
      with:
        java-version: 21

    - name: Build project with Maven
      run: mvn -B clean compile package --file pom.xml
