name: Maven CI/CD

on:
 workflow_dispatch:
 pull_request:
    branches: [ master ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 21
        uses: actions/setup-java@v1
        with:
          java-version: 21
      - name: Build project with Maven
        run: mvn -B clean compile package --file pom.xml
      - run: mkdir staging
      - run: ls
      - name: Publish to GitHub Packages Apache Maven
        run: cp target/*jar-with-dependencies.jar staging
      - name: Publish to GitHub Packages Apache Maven
        uses: actions/upload-artifact@v1
        with:
          name: Package
          path: staging